// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260413231513_AddMetaSuggestions")]
    partial class AddMetaSuggestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Application.Features.Emoji.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Meta.MetaSuggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Anonymity")
                        .HasColumnType("integer");

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ForumChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<long?>("ThreadChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("ThreadChannelId")
                        .IsUnique();

                    b.HasIndex("GuildId", "State");

                    b.ToTable("MetaSuggestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MetaSuggestions_Motivation_NotBlank", "length(btrim(\"Motivation\")) > 0");

                            t.HasCheckConstraint("CK_MetaSuggestions_Specification_NotBlank", "length(btrim(\"Specification\")) > 0");

                            t.HasCheckConstraint("CK_MetaSuggestions_Summary_NotBlank", "length(btrim(\"Summary\")) > 0");

                            t.HasCheckConstraint("CK_MetaSuggestions_Title_NotBlank", "length(btrim(\"Title\")) > 0");
                        });
                });

            modelBuilder.Entity("RatBot.Infrastructure.Settings.MetaSuggestionSettingsEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestForumChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MetaSuggestionSettings", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Features.Quorum.QuorumSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<double>("QuorumProportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double precision");

                    b.HasKey("GuildId", "TargetType", "TargetId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "TargetType");

                    b.ToTable("QuorumConfigs", (string)null);
                });

            modelBuilder.Entity("RatBot.Infrastructure.Settings.Quorum.RoleEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId", "TargetType", "TargetId", "RoleId");

                    b.ToTable("QuorumConfigRoles", (string)null);
                });

            modelBuilder.Entity("RatBot.Infrastructure.Settings.Quorum.RoleEntity", b =>
                {
                    b.HasOne("RatBot.Domain.Features.Quorum.QuorumSettings", null)
                        .WithMany()
                        .HasForeignKey("GuildId", "TargetType", "TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
