// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260410000712_NormalizeQuorumConfigurations")]
    partial class NormalizeQuorumConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Entities.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts");
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumScopeConfigEntity", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScopeId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("QuorumProportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double precision");

                    b.HasKey("GuildId", "ScopeType", "ScopeId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "ScopeType");

                    b.ToTable("QuorumScopeConfigs", (string)null);
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumScopeConfigRoleEntity", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScopeId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "ScopeType", "ScopeId", "RoleId");

                    b.ToTable("QuorumScopeConfigRoles", (string)null);
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumScopeConfigRoleEntity", b =>
                {
                    b.HasOne("RatBot.Infrastructure.Configuration.Quorum.QuorumScopeConfigEntity", "Config")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId", "ScopeType", "ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumScopeConfigEntity", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
