// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260429005304_NullablesInnit")]
    partial class NullablesInnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Emoji.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Meta.MetaSuggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ForumChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<long?>("ThreadChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("ThreadChannelId")
                        .IsUnique();

                    b.HasIndex("GuildId", "State");

                    b.ToTable("MetaSuggestions", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Meta.MetaSuggestionSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestForumChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MetaSuggestionSettings", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Moderation.AutobannedUser", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("BannedUser")
                        .HasColumnType("bigint");

                    b.Property<long>("Moderator")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "BannedUser");

                    b.HasIndex("BannedUser");

                    b.HasIndex("GuildId");

                    b.HasIndex("Moderator");

                    b.ToTable("AutobannedUsers", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<double>("Proportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double precision");

                    b.HasKey("GuildId", "TargetType", "TargetId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "TargetType");

                    b.ToTable("QuorumConfigs", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettingsRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    b.HasKey("GuildId", "TargetType", "TargetId", "Id");

                    b.ToTable("QuorumConfigRoles", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.RoleColours.MemberColourPreference", b =>
                {
                    b.Property<Guid>("PreferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PreferenceId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MemberColourPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberColourPreferences_ConfiguredOption_SelectedOption_NotNull", "(\"Kind\" <> 1) OR (\"SelectedOptionId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MemberColourPreferences_NoColour_SelectedOption_Null", "(\"Kind\" <> 2) OR (\"SelectedOptionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.RoleColours.RoleColourOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DisplayRoleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalisedKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SourceRoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OptionId");

                    b.HasIndex("DisplayRoleId")
                        .IsUnique();

                    b.HasIndex("NormalisedKey")
                        .IsUnique();

                    b.HasIndex("SourceRoleId", "DisplayRoleId")
                        .IsUnique();

                    b.ToTable("RoleColourOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoleColourOptions_DifferentRoles", "\"SourceRoleId\" <> \"DisplayRoleId\"");

                            t.HasCheckConstraint("CK_RoleColourOptions_Key_NotBlank", "length(btrim(\"Key\")) > 0");

                            t.HasCheckConstraint("CK_RoleColourOptions_Label_NotBlank", "length(btrim(\"Label\")) > 0");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettingsRole", b =>
                {
                    b.HasOne("RatBot.Domain.Quorum.QuorumSettings", null)
                        .WithMany("Roles")
                        .HasForeignKey("GuildId", "TargetType", "TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatBot.Domain.RoleColours.MemberColourPreference", b =>
                {
                    b.HasOne("RatBot.Domain.RoleColours.RoleColourOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettings", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
