// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260406235256_AddConfigRelations")]
    partial class AddConfigRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Entities.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts");
                });

            modelBuilder.Entity("RatBot.Infrastructure.Data.ConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("jsonb");

                    b.HasKey("Key", "Value");

                    b.ToTable("Configs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
