// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260222043850_InitialOracleMySql")]
    partial class InitialOracleMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RatBot.Domain.Entities.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.QuorumScopeConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("ScopeType")
                        .HasColumnType("int");

                    b.Property<ulong>("ScopeId")
                        .HasColumnType("bigint unsigned");

                    b.Property<double>("QuorumProportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId", "ScopeType", "ScopeId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "ScopeType");

                    b.ToTable("QuorumScopeConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
