// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260331224348_AddVirtueRoleTierConfigs")]
    partial class AddVirtueRoleTierConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RatBot.Domain.Entities.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.EmojiVirtue", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Virtue")
                        .HasColumnType("int")
                        .HasColumnName("Score");

                    b.HasKey("EmojiId");

                    b.ToTable("ReactionEmojiScores");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.QuorumScopeConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("ScopeType")
                        .HasColumnType("int");

                    b.Property<ulong>("ScopeId")
                        .HasColumnType("bigint unsigned");

                    b.Property<double>("QuorumProportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId", "ScopeType", "ScopeId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "ScopeType");

                    b.ToTable("QuorumScopeConfigs");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.UserVirtue", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Virtue")
                        .HasColumnType("int")
                        .HasColumnName("Score");

                    b.HasKey("UserId");

                    b.ToTable("UserScores");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.VirtueRoleTierConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("TierIndex")
                        .HasColumnType("int");

                    b.Property<int>("MaxVirtue")
                        .HasColumnType("int");

                    b.Property<int>("MinVirtue")
                        .HasColumnType("int");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId", "TierIndex");

                    b.HasIndex("GuildId");

                    b.ToTable("VirtueRoleTierConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
