// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260404033000_RemoveGuildConfig")]
    partial class RemoveGuildConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Entities.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts");
                });

            modelBuilder.Entity("RatBot.Domain.Entities.QuorumScopeConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ScopeId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("QuorumProportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double precision");

                    b.Property<string>("RoleIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("GuildId", "ScopeType", "ScopeId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "ScopeType");

                    b.ToTable("QuorumScopeConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
