// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations;

[DbContext(typeof(BotDbContext))]
partial class BotDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("RatBot.Domain.Entities.EmojiUsageCount", b =>
        {
            b.Property<string>("EmojiId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<int>("UsageCount")
                .HasColumnType("integer");

            b.HasKey("EmojiId");

            b.ToTable("EmojiUsageCounts");
        });

        modelBuilder.Entity("RatBot.Domain.Entities.GuildConfig", b =>
        {
            b.Property<ulong>("GuildId")
                .HasColumnType("numeric(20,0)");

            b.Property<string>("Prefix")
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnType("character varying(2)");

            b.HasKey("GuildId");

            b.ToTable("GuildConfigs");
        });

        modelBuilder.Entity("RatBot.Domain.Entities.QuorumScopeConfig", b =>
        {
            b.Property<ulong>("GuildId")
                .HasColumnType("numeric(20,0)");

            b.Property<int>("ScopeType")
                .HasColumnType("integer");

            b.Property<ulong>("ScopeId")
                .HasColumnType("numeric(20,0)");

            b.Property<double>("QuorumProportion")
                .HasPrecision(6, 4)
                .HasColumnType("double precision");

            b.Property<string>("RoleIds")
                .IsRequired()
                .HasColumnType("jsonb");

            b.HasKey("GuildId", "ScopeType", "ScopeId");

            b.HasIndex("GuildId");

            b.HasIndex("GuildId", "ScopeType");

            b.ToTable("QuorumScopeConfigs");
        });

#pragma warning restore 612, 618
    }
}
